version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ebay-mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: Ebay_clone_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always

  # springboot-app:
  #   build: .
  #   container_name: ebay-springboot
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     SPRING_DATASOURCE_URL: ${DB_URL}
  #   ports:
  #     - "8082:8082"
  #   restart: on-failure
volumes:
  mysql_data:
